on:
  repository_dispatch:
    types: [new_image]

name: Build and Push to ECR
jobs:
  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Verify Terraform version
      run: terraform --version
      working-directory: deploy/iac/terraform/prod

    - name: Terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform init -input=false
      working-directory: deploy/iac/terraform/prod

    - name: Terraform validation
      run: terraform validate
      working-directory: deploy/iac/terraform/prod

    - name: Terraform apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform apply -auto-approve -input=false
      working-directory: deploy/iac/terraform/prod
